# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('second_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('postal_code', models.IntegerField(blank=True, max_length=5)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
