# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_auto_20171019_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
