# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_auto_20171019_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
