# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_remove_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
    ]
