# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0016_auto_20171023_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
