# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competition',
            new_name='Competitions',
        ),
    ]
