# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0003_competitions_attending_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(blank=True, upload_to='')),
                ('attending_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.Competitions')),
            ],
        ),
    ]
